######################################################################
# Automatically generated by qmake (2.01a) Sa. Jan 25 21:23:55 2014
######################################################################

TEMPLATE = app
TARGET = helloworldqt
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

