######################################################################
# Automatically generated by qmake (2.01a) Di. Feb 11 13:13:35 2014
######################################################################

TEMPLATE = app
TARGET = canmon
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += *.h
SOURCES += *.cpp
